# Generated by Django 4.0 on 2022-07-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_ouruser_delete_account'),
        ('clothes', '0002_city_country_person_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_id', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=40)),
                ('coat_id', models.CharField(default='', max_length=40)),
                ('top_id', models.CharField(default='', max_length=40)),
                ('pants_id', models.CharField(default='', max_length=40)),
                ('dress_id', models.CharField(default='', max_length=40)),
                ('max_tem_id', models.IntegerField()),
                ('min_tem_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClothesKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('outer', 'outer'), ('top', 'top'), ('pants', 'pants'), ('onepiece', 'onepiece')], default='', max_length=10)),
                ('length', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('fit', models.CharField(max_length=40)),
                ('pattern_print', models.CharField(max_length=40)),
                ('material', models.CharField(max_length=40)),
                ('neck_line', models.CharField(default='False', max_length=40)),
                ('sleeve_length', models.CharField(default='False', max_length=40)),
                ('top_detail', models.CharField(default='False', max_length=40)),
                ('clothes_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_user', models.BooleanField(default=False)),
                ('my_clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ouruser')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
