# Generated by Django 4.0 on 2022-07-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_clothes_clotheskind_likes_remove_person_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='style',
            field=models.CharField(choices=[('simplebasic', 'simple&basic'), ('lovely', 'lovely'), ('sexyglam', 'sexy'), ('unique', 'unique'), ('vintage', 'vintage'), ('casual', 'casual'), ('etc', 'etc')], default='', max_length=40),
        ),
    ]
