# Generated by Django 4.0 on 2022-08-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_clothes_image_alter_clothes_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='coat_id',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='dress_id',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='pants_id',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='top_id',
        ),
        migrations.AddField(
            model_name='clothes',
            name='onepiece',
            field=models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='outer',
            field=models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='pants',
            field=models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='top',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothes_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ClothesKind',
        ),
    ]
