# Generated by Django 4.0 on 2022-08-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_rename_user_likes_user_id_remove_clothes_coat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='clothes_id',
            new_name='max_tem',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='max_tem_id',
            new_name='min_tem',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='outer',
            new_name='outerwear',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='my_clothes',
            new_name='clothes_id',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='like_user',
            new_name='like_select',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='min_tem_id',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
