# Generated by Django 4.0.4 on 2022-08-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_rename_clothes_id_clothes_max_tem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.CharField(max_length=40)),
                ('gu', models.CharField(max_length=40)),
                ('dong', models.CharField(max_length=40)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gu',
            name='si',
        ),
        migrations.RemoveField(
            model_name='region',
            name='dong',
        ),
        migrations.RemoveField(
            model_name='region',
            name='gu',
        ),
        migrations.RemoveField(
            model_name='region',
            name='si',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(blank=True, upload_to='clothes'),
        ),
        migrations.DeleteModel(
            name='Dong',
        ),
        migrations.DeleteModel(
            name='Gu',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Si',
        ),
    ]
