# Generated by Django 4.0.4 on 2022-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_location_remove_gu_si_remove_region_dong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('si', models.CharField(max_length=40)),
                ('gu', models.CharField(max_length=40)),
                ('dong', models.CharField(max_length=40)),
            ],
        ),
    ]
