# Generated by Django 4.0.4 on 2022-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_mylocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotheStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('user_style', models.CharField(max_length=40)),
            ],
        ),
    ]
