# Generated by Django 4.0 on 2022-07-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('gender', models.CharField(default='woman', max_length=6)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
